import { IconName } from '@/global'

interface CategoryIcon {
  icon: IconName
  text: string
}

export const categoriesIcons: CategoryIcon[] = [
  { icon: 'restaurant-outline', text: 'Comida fuera' },
  { icon: 'fast-food-outline', text: 'Comida rápida' },
  { icon: 'cafe-outline', text: 'Café' },
  { icon: 'car-outline', text: 'Auto' },
  { icon: 'bus-outline', text: 'Transporte público' },
  { icon: 'bicycle-outline', text: 'Bicicleta' },
  { icon: 'train-outline', text: 'Tren' },
  { icon: 'home-outline', text: 'Vivienda' },
  { icon: 'bed-outline', text: 'Dormitorio' },
  { icon: 'construct-outline', text: 'Reparaciones' },
  { icon: 'school-outline', text: 'Educación' },
  { icon: 'book-outline', text: 'Libros' },
  { icon: 'pencil-outline', text: 'Útiles escolares' },
  { icon: 'medkit-outline', text: 'Salud' },
  { icon: 'heart-outline', text: 'Bienestar' },
  { icon: 'fitness-outline', text: 'Ejercicio' },
  { icon: 'briefcase-outline', text: 'Trabajo' },
  { icon: 'document-text-outline', text: 'Papelería' },
  { icon: 'calendar-outline', text: 'Agenda' },
  { icon: 'game-controller-outline', text: 'Videojuegos' },
  { icon: 'musical-notes-outline', text: 'Música' },
  { icon: 'film-outline', text: 'Películas' },
  { icon: 'airplane-outline', text: 'Viajes' },
  { icon: 'cart-outline', text: 'Supermercado' },
  { icon: 'bag-outline', text: 'Compras' },
  { icon: 'pricetags-outline', text: 'Descuentos' },
  { icon: 'bulb-outline', text: 'Electricidad' },
  { icon: 'water-outline', text: 'Agua' },
  { icon: 'tv-outline', text: 'Servicios TV/Internet' },
  { icon: 'people-outline', text: 'Familia' },
  { icon: 'woman-outline', text: 'Gastos personales (ella)' },
  { icon: 'man-outline', text: 'Gastos personales (él)' },
  { icon: 'wallet-outline', text: 'Cartera' },
  { icon: 'cash-outline', text: 'Efectivo' },
  { icon: 'card-outline', text: 'Tarjeta' },
  { icon: 'star-outline', text: 'Favoritos' },
  { icon: 'gift-outline', text: 'Regalos' },
  { icon: 'warning-outline', text: 'Imprevistos' },
  { icon: 'ellipsis-horizontal-outline', text: 'Otros' },
]

export const COLORS = [
  '#6366f1',
  '#84cc16',
  '#ec4899',
  '#f59e0b',
  '#14b8a6',
  '#FF0000',
  '#00FF00',
  '#0000FF',
  '#FFFF00',
  '#FF00FF',
  '#00FFFF',
  '#FFA500',
  '#800080',
  '#008000',
  '#000080',
  '#808000',
  '#FFC0CB',
  '#A52A2A',
  '#808080',
  '#000000',
  '#ADD8E6',
  '#90EE90',
  '#D2691E',
  '#F5DEB3',
]
